package com.sale.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Insured generated by hbm2java
 */
@Entity
@Table(name = "insured", catalog = "sale_db")
public class Insured implements Serializable {
	
	private int id;
	private HolderBill holderBill;
	private String insuredName;
	private String rel;
	private Integer level;

	public Insured() {
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BILL_ID")
	public HolderBill getHolderBill() {
		return this.holderBill;
	}

	public void setHolderBill(HolderBill holderBill) {
		this.holderBill = holderBill;
	}

	@Column(name = "INSURED_NAME", nullable = false, length = 20)
	public String getInsuredName() {
		return this.insuredName;
	}

	public void setInsuredName(String insuredName) {
		this.insuredName = insuredName;
	}

	@Column(name = "REL", nullable = false, length = 20)
	public String getRel() {
		return this.rel;
	}

	public void setRel(String rel) {
		this.rel = rel;
	}

	@Column(name = "LEVEL",nullable = false)
	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer Level) {
		this.level = Level;
	}
}
