package com.query.entity;
// Generated 2018-3-13 13:22:29 by Hibernate Tools 5.2.8.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import java.io.Serializable;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clerk generated by hbm2java
 */
@Entity
@Table(name = "clerk", catalog = "sale_db")
public class Clerk implements Serializable {

	private static final long serialVersionUID = -8996207189981918038L;

	private int clerkId;
	private String password;
	private String headImg;
	private String clerkName;
	private Date birthday;
	private String mobile;
	private String note;
	private String sex;
	private Integer saleNum;
	private Set<HolderBill> holderBills = new HashSet<>();

	public Clerk() { }

	@Id
	@GeneratedValue
	@Column(name = "CLERK_ID", unique = true, nullable = false)
	public int getClerkId() {
		return this.clerkId;
	}

	public void setClerkId(int clerkId) {
		this.clerkId = clerkId;
	}

	@Column(name = "PASSWORD", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "HEAD_IMG")
	public String getHeadImg() {
		return headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	@Column(name = "CLERK_NAME")
	public String getClerkName() {
		return clerkName;
	}

	public void setClerkName(String clerkName) {
		this.clerkName = clerkName;
	}

	@Column(name = "BIRTHDAY")
	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "MOBILE")
	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "NOTE")
	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "SEX")
	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Transient
	public Integer getSaleNum() {
		return saleNum;
	}

	public void setSaleNum(Integer saleNum) {
		this.saleNum = saleNum;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "clerk")
	public Set<HolderBill> getHolderBills() {
		return this.holderBills;
	}

	public void setHolderBills(Set<HolderBill> holderBills) {
		this.holderBills = holderBills;
	}

}
