package com.query.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HolderBill generated by hbm2java
 */
@Entity
@Table(name = "holder_bill", catalog = "sale_db")
public class HolderBill implements java.io.Serializable {

	private static final long serialVersionUID = 8891204726908177222L;
	
	private int id;
	private Clerk clerk;
	private String holderName;
	private String sex;
	private Date birthDate;
	private String mobile;
	private String polName;
	private BigDecimal money;
	private String baodanNo;
	private Date inforceTime;
	private int clerkID;
	private Set<Insured> insureds = new HashSet<>();

	public HolderBill() { }

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CLERK_ID", nullable = false)
	public Clerk getClerk() {
		return this.clerk;
	}

	public void setClerk(Clerk clerk) {
		this.clerk = clerk;
	}

	@Column(name = "HOLDER_NAME", nullable = false, length = 20)
	public String getHolderName() {
		return this.holderName;
	}

	public void setHolderName(String holderName) {
		this.holderName = holderName;
	}

	@Column(name = "SEX", nullable = false, length = 3)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BIRTH_DATE", nullable = false, length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "MOBILE", nullable = false, length = 11)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "POL_NAME", nullable = false, length = 5)
	public String getPolName() {
		return this.polName;
	}

	public void setPolName(String polName) {
		this.polName = polName;
	}

	@Column(name = "MONEY", nullable = false, precision = 9)
	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	@Column(name = "BAODAN_NO", nullable = false, length = 30)
	public String getBaodanNo() {
		return this.baodanNo;
	}

	public void setBaodanNo(String baodanNo) {
		this.baodanNo = baodanNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INFORCE_TIME", nullable = false, length = 19)
	public Date getInforceTime() {
		return this.inforceTime;
	}

	public void setInforceTime(Date inforceTime) {
		this.inforceTime = inforceTime;
	}

	@Transient
	public int getClerkID() {
		return clerkID;
	}

	public void setClerkID(int clerkID) {
		this.clerkID = clerkID;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "holderBill")
	public Set<Insured> getInsureds() {
		return this.insureds;
	}

	public void setInsureds(Set<Insured> insureds) {
		this.insureds = insureds;
	}

}
